export const AUTH_MESSAGES = {
    INACTIVE: 'Account is inactive',
    PHONE_EXIST: 'Provided phone number is already registered with another account',
    EMAIL_EXIST: 'Email is already associated with some other account.',
    TOKEN_SEND_ALREADY: 'Token already sent. Please wait',
    TOKEN_SENT: 'Token has been sent to provided address',
    INVALID_OTP: 'Invalid OTP provided',
    PASSWORD_RESET: 'Password has been updated',
    INVALID_PASSWORD: 'Old Password didn\'t matched',
    PROFILE_UPDATED: 'Profile has been updated',
    BIOMETRIC_UPDATED:'Biometric added successfully',
    NOT_FOUND: 'Requested data does not exist',
    INVALID_AUTH_TOKEN: 'Invalid Auth Token',
    MISSING_AUTH_HEADER: 'Missing Authorization Header',
    MISSING_USER_INFO: 'User information not found',
    PAYMENT_NOT_VERIFIED: "Payment not verified",
    PAYMENT_NOT_ADDED: "Please Add a Payment Method",
    AUTH_HEADER_MISSING: 'Missing Authorization Header',
    INVALID_AUTH_PROVIDER: 'Not Supported Auth provider',
    INVALID_BEARER_TOKEN:
      'Invalid Authorization token - Token does not match Bearer .*',
    INVALID_SESSION_IN_REDIS:
      'NO session found in Redis, Invalid Session',
    INVALID_SOCKET_PROVIDER: 'Not Supported Socket provider',
    INVALID_PUSHER_CLIENT:
      'Invalid pusher client, Please send valid socketId for client',
    USER_EXIST: 'User with Same email already exists',
    USER_CREATED: 'User Created Successfully',
    LOGIN: 'Your signin was successful. Redirecting...',
    LOGIN_ERROR: 'Invalid email or password provided',
    CHANGEPWD_ERROR: 'Something went wrong while changing the Password. Please contact Support.',
    ROLE_INVALID: 'Invalid Role provided.',
    INVALID_REQUSET: 'Invalid Request',
    USER_NOT_FOUND: 'User not found',
    USERNAME_EXIST: 'Username already exist',
  }